POST http://localhost:8080/events
content-type: application/json

{
	"name": "Go Meetup",
	"description": "Learn Go with friends",
	"location": "Online",
	"dateTime": "2025-04-01T17:20:000Z"
}


